/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.gre.comp1549.dashboard.controls;

/**
 *
 * @author st8511x
 */
public class ArrivalBoard extends javax.swing.JPanel {

    /**
     * Creates new form testBean
     */
    public ArrivalBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdStatus = new javax.swing.JComboBox();
        panEnterDate = new javax.swing.JPanel();
        cmdHrs = new javax.swing.JComboBox();
        cmdMins = new javax.swing.JComboBox();
        cmdAmPm = new javax.swing.JComboBox();
        txtDestination = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        board = new myjavabean.Bean();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Status");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Arrival:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Destination");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Time");

        cmdStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "On Time", "Delayed ", "Cancelled" }));

        panEnterDate.setLayout(new java.awt.GridBagLayout());

        cmdHrs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdHrs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cmdHrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHrsActionPerformed(evt);
            }
        });
        panEnterDate.add(cmdHrs, new java.awt.GridBagConstraints());

        cmdMins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmdMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMinsActionPerformed(evt);
            }
        });
        panEnterDate.add(cmdMins, new java.awt.GridBagConstraints());

        cmdAmPm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdAmPm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "am", "pm" }));
        cmdAmPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAmPmActionPerformed(evt);
            }
        });
        panEnterDate.add(cmdAmPm, new java.awt.GridBagConstraints());

        txtDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinationActionPerformed(evt);
            }
        });

        btnShow.setText("show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panEnterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnShow)
                                .addGap(26, 26, 26)
                                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdStatus)
                    .addComponent(panEnterDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShow)
                    .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void cmdMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMinsActionPerformed

    private void cmdHrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdHrsActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        String strDest = String.format(txtDestination.getText());
        String strHrs = "" + cmdHrs.getSelectedItem();
        String strMins = "" + cmdMins.getSelectedItem();
        String strAMPM = "" + cmdAmPm.getSelectedItem();
        String strStatus = "" + cmdStatus.getSelectedItem();
        
        board.setDestination(strDest);
        board.setHrs(strHrs);
        board.setMins(strMins);
        board.setAMPM(strAMPM);
        board.setStatus(strStatus);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void cmdAmPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAmPmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdAmPmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myjavabean.Bean board;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox cmdAmPm;
    private javax.swing.JComboBox cmdHrs;
    private javax.swing.JComboBox cmdMins;
    private javax.swing.JComboBox cmdStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panEnterDate;
    private javax.swing.JTextField txtDestination;
    // End of variables declaration//GEN-END:variables
}
