/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myjavabean;

/**
 *
 * @author st8511x
 */
public class Bean extends javax.swing.JPanel {

    /**
     * Creates new form Bean
     */
    public Bean() {
        initComponents();
    }
        public String getDestination() {
        return lblDestination.getText();
    }

    public void setDestination(String dest) {
        lblDestination.setText(dest);
    }
    
    public String getHrs() {
        return lbllHrs.getText();
    }
    
    public void setHrs(String hrs){
        lbllHrs.setText(hrs);
    }
    
    public String getMins() {
        return lblMins.getText();
    }
    
    public void setMins(String mins){
        lblMins.setText(mins);
    }
    
     public String getAMPM() {
        return lblAMPM.getText();
    }
    
    public void setAMPM(String ampm){
        lblAMPM.setText(ampm);
    }
    
    public String getStatus() {
        return lblStatus.getText();
    }
    
    public void setStatus(String status){
        lblStatus.setText(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDestination = new javax.swing.JLabel();
        lbllHrs = new javax.swing.JLabel();
        lblMins = new javax.swing.JLabel();
        lblAMPM = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        lblDestination.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDestination.setText("destination");
        lblDestination.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblDestination);

        lbllHrs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbllHrs.setText("hrs");
        lbllHrs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lbllHrs);

        lblMins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMins.setText("mins");
        lblMins.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblMins);

        lblAMPM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAMPM.setText("ampm");
        lblAMPM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblAMPM);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setText("status");
        lblStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblStatus);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAMPM;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblMins;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lbllHrs;
    // End of variables declaration//GEN-END:variables
}
